defaults:
  - _self_
  - embeddings/transform:
    - shuffle_pad

name: imagenet_embeddings
embeddings:
  train_path: ./src/data/embeddings/ImageNet50K_emb_simsiam_train_dataset_noised.pt
  train_path2: ./src/data/embeddings/ImageNet50K_emb_simsiam_train_dataset_noised_2.pt
  test_path: ./src/data/embeddings/ImageNet_emb_simsiam_val_dataset.pt
  class_number: 1000
hparams:
  train_epochs_reference_classifier: 100
  train_epochs_mapper: 50
#    train_mb_size: 64
#    eval_mb_size: 64
  lr_reference_classifier: 0.00001
#    gamma: floa
  lr_mapper: 0.00001
subsets: [10, 50, 100, 500, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 10000, 50000]