defaults:
  - _self_
  - embeddings/transform:
    - affine

name: imagenet_embeddings
embeddings:
  train_path: ./src/data/embeddings/ImageNet50K_emb_train_dataset.pt
  test_path: ./src/data/embeddings/ImageNet_emb_val_dataset.pt
  class_number: 1000
hparams:
  train_epochs_reference_classifier: 50
  train_epochs_mapper: 50
#    train_mb_size: 64
#    eval_mb_size: 64
  lr_reference_classifier: 0.00001
#    gamma: float
  lr_mapper: 0.00001
subsets: [100, 500, 1000, 2000, 3000, 4000, 5000, 10000]